//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string ImageFilePath { get; set; }
        public string Description { get; set; }
        public int Duration { get; set; }
        public int CatID { get; set; }
        public int NumViews { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
